use crate::{
    input::{
        buttons::{GamepadButton, ToGamepadButton},
        keys::{KeyCode, Mod, ToKeyCode, ToMod},
        GamepadEvent, KeyEvent, ToInputId,
    },
    settings::gui::{GuiEvent, ToGuiEvent},
};

impl ToGuiEvent for sdl2::event::Event {
    fn to_gui_event(&self) -> Option<GuiEvent> {
        match self {
            sdl2::event::Event::KeyDown {
                keycode: Some(keycode),
                repeat: false,
                keymod,
                ..
            } => {
                //keymod && sdl2::keyboard::Mod::LSHIFTMOD != 0;
                keycode.to_key_code().map(|key_code| {
                    GuiEvent::Keyboard(KeyEvent::Pressed(
                        key_code,
                        keymod.to_mod().unwrap_or(Mod::NOMOD),
                    ))
                })
            }

            sdl2::event::Event::KeyUp {
                keycode: Some(keycode),
                repeat: false,
                keymod,
                ..
            } => keycode.to_key_code().map(|key_code| {
                GuiEvent::Keyboard(KeyEvent::Released(
                    key_code,
                    keymod.to_mod().unwrap_or(Mod::NOMOD),
                ))
            }),

            sdl2::event::Event::ControllerDeviceAdded { which, .. } => {
                Some(GuiEvent::Gamepad(GamepadEvent::ControllerAdded {
                    which: which.to_input_id(),
                }))
            }
            sdl2::event::Event::ControllerDeviceRemoved { which, .. } => {
                Some(GuiEvent::Gamepad(GamepadEvent::ControllerRemoved {
                    which: which.to_input_id(),
                }))
            }
            sdl2::event::Event::ControllerButtonDown { which, button, .. } => {
                button.to_gamepad_button().map(|button| {
                    GuiEvent::Gamepad(GamepadEvent::ButtonDown {
                        which: which.to_input_id(),
                        button,
                    })
                })
            }
            sdl2::event::Event::ControllerButtonUp { which, button, .. } => {
                button.to_gamepad_button().map(|button| {
                    GuiEvent::Gamepad(GamepadEvent::ButtonUp {
                        which: which.to_input_id(),
                        button,
                    })
                })
            }
            _ => None,
        }
    }
}

impl ToKeyCode for sdl2::keyboard::Keycode {
    fn to_key_code(&self) -> Option<KeyCode> {
        use self::KeyCode::*;
        match self {
            sdl2::keyboard::Keycode::Backspace => Some(Backspace),
            sdl2::keyboard::Keycode::Tab => Some(Tab),
            sdl2::keyboard::Keycode::Return => Some(Return),
            sdl2::keyboard::Keycode::Escape => Some(Escape),
            sdl2::keyboard::Keycode::Space => Some(Space),
            sdl2::keyboard::Keycode::Exclaim => Some(Exclaim),
            sdl2::keyboard::Keycode::Quotedbl => Some(Quotedbl),
            sdl2::keyboard::Keycode::Hash => Some(Hash),
            sdl2::keyboard::Keycode::Dollar => Some(Dollar),
            sdl2::keyboard::Keycode::Percent => Some(Percent),
            sdl2::keyboard::Keycode::Ampersand => Some(Ampersand),
            sdl2::keyboard::Keycode::Quote => Some(Quote),
            sdl2::keyboard::Keycode::LeftParen => Some(LeftParen),
            sdl2::keyboard::Keycode::RightParen => Some(RightParen),
            sdl2::keyboard::Keycode::Asterisk => Some(Asterisk),
            sdl2::keyboard::Keycode::Plus => Some(Plus),
            sdl2::keyboard::Keycode::Comma => Some(Comma),
            sdl2::keyboard::Keycode::Minus => Some(Minus),
            sdl2::keyboard::Keycode::Period => Some(Period),
            sdl2::keyboard::Keycode::Slash => Some(Slash),
            sdl2::keyboard::Keycode::Num0 => Some(Num0),
            sdl2::keyboard::Keycode::Num1 => Some(Num1),
            sdl2::keyboard::Keycode::Num2 => Some(Num2),
            sdl2::keyboard::Keycode::Num3 => Some(Num3),
            sdl2::keyboard::Keycode::Num4 => Some(Num4),
            sdl2::keyboard::Keycode::Num5 => Some(Num5),
            sdl2::keyboard::Keycode::Num6 => Some(Num6),
            sdl2::keyboard::Keycode::Num7 => Some(Num7),
            sdl2::keyboard::Keycode::Num8 => Some(Num8),
            sdl2::keyboard::Keycode::Num9 => Some(Num9),
            sdl2::keyboard::Keycode::Colon => Some(Colon),
            sdl2::keyboard::Keycode::Semicolon => Some(Semicolon),
            sdl2::keyboard::Keycode::Less => Some(Less),
            sdl2::keyboard::Keycode::Equals => Some(Equals),
            sdl2::keyboard::Keycode::Greater => Some(Greater),
            sdl2::keyboard::Keycode::Question => Some(Question),
            sdl2::keyboard::Keycode::At => Some(At),
            sdl2::keyboard::Keycode::LeftBracket => Some(LeftBracket),
            sdl2::keyboard::Keycode::Backslash => Some(Backslash),
            sdl2::keyboard::Keycode::RightBracket => Some(RightBracket),
            sdl2::keyboard::Keycode::Caret => Some(Caret),
            sdl2::keyboard::Keycode::Underscore => Some(Underscore),
            sdl2::keyboard::Keycode::Backquote => Some(Backquote),
            sdl2::keyboard::Keycode::A => Some(A),
            sdl2::keyboard::Keycode::B => Some(B),
            sdl2::keyboard::Keycode::C => Some(C),
            sdl2::keyboard::Keycode::D => Some(D),
            sdl2::keyboard::Keycode::E => Some(E),
            sdl2::keyboard::Keycode::F => Some(F),
            sdl2::keyboard::Keycode::G => Some(G),
            sdl2::keyboard::Keycode::H => Some(H),
            sdl2::keyboard::Keycode::I => Some(I),
            sdl2::keyboard::Keycode::J => Some(J),
            sdl2::keyboard::Keycode::K => Some(K),
            sdl2::keyboard::Keycode::L => Some(L),
            sdl2::keyboard::Keycode::M => Some(M),
            sdl2::keyboard::Keycode::N => Some(N),
            sdl2::keyboard::Keycode::O => Some(O),
            sdl2::keyboard::Keycode::P => Some(P),
            sdl2::keyboard::Keycode::Q => Some(Q),
            sdl2::keyboard::Keycode::R => Some(R),
            sdl2::keyboard::Keycode::S => Some(S),
            sdl2::keyboard::Keycode::T => Some(T),
            sdl2::keyboard::Keycode::U => Some(U),
            sdl2::keyboard::Keycode::V => Some(V),
            sdl2::keyboard::Keycode::W => Some(W),
            sdl2::keyboard::Keycode::X => Some(X),
            sdl2::keyboard::Keycode::Y => Some(Y),
            sdl2::keyboard::Keycode::Z => Some(Z),
            sdl2::keyboard::Keycode::Delete => Some(Delete),
            sdl2::keyboard::Keycode::CapsLock => Some(CapsLock),
            sdl2::keyboard::Keycode::F1 => Some(F1),
            sdl2::keyboard::Keycode::F2 => Some(F2),
            sdl2::keyboard::Keycode::F3 => Some(F3),
            sdl2::keyboard::Keycode::F4 => Some(F4),
            sdl2::keyboard::Keycode::F5 => Some(F5),
            sdl2::keyboard::Keycode::F6 => Some(F6),
            sdl2::keyboard::Keycode::F7 => Some(F7),
            sdl2::keyboard::Keycode::F8 => Some(F8),
            sdl2::keyboard::Keycode::F9 => Some(F9),
            sdl2::keyboard::Keycode::F10 => Some(F10),
            sdl2::keyboard::Keycode::F11 => Some(F11),
            sdl2::keyboard::Keycode::F12 => Some(F12),
            sdl2::keyboard::Keycode::PrintScreen => Some(PrintScreen),
            sdl2::keyboard::Keycode::ScrollLock => Some(ScrollLock),
            sdl2::keyboard::Keycode::Pause => Some(Pause),
            sdl2::keyboard::Keycode::Insert => Some(Insert),
            sdl2::keyboard::Keycode::Home => Some(Home),
            sdl2::keyboard::Keycode::PageUp => Some(PageUp),
            sdl2::keyboard::Keycode::End => Some(End),
            sdl2::keyboard::Keycode::PageDown => Some(PageDown),
            sdl2::keyboard::Keycode::Right => Some(Right),
            sdl2::keyboard::Keycode::Left => Some(Left),
            sdl2::keyboard::Keycode::Down => Some(Down),
            sdl2::keyboard::Keycode::Up => Some(Up),
            sdl2::keyboard::Keycode::NumLockClear => Some(NumLockClear),
            sdl2::keyboard::Keycode::KpDivide => Some(KpDivide),
            sdl2::keyboard::Keycode::KpMultiply => Some(KpMultiply),
            sdl2::keyboard::Keycode::KpMinus => Some(KpMinus),
            sdl2::keyboard::Keycode::KpPlus => Some(KpPlus),
            sdl2::keyboard::Keycode::KpEnter => Some(KpEnter),
            sdl2::keyboard::Keycode::Kp1 => Some(Kp1),
            sdl2::keyboard::Keycode::Kp2 => Some(Kp2),
            sdl2::keyboard::Keycode::Kp3 => Some(Kp3),
            sdl2::keyboard::Keycode::Kp4 => Some(Kp4),
            sdl2::keyboard::Keycode::Kp5 => Some(Kp5),
            sdl2::keyboard::Keycode::Kp6 => Some(Kp6),
            sdl2::keyboard::Keycode::Kp7 => Some(Kp7),
            sdl2::keyboard::Keycode::Kp8 => Some(Kp8),
            sdl2::keyboard::Keycode::Kp9 => Some(Kp9),
            sdl2::keyboard::Keycode::Kp0 => Some(Kp0),
            sdl2::keyboard::Keycode::KpPeriod => Some(KpPeriod),
            sdl2::keyboard::Keycode::Application => Some(Application),
            sdl2::keyboard::Keycode::Power => Some(Power),
            sdl2::keyboard::Keycode::KpEquals => Some(KpEquals),
            sdl2::keyboard::Keycode::F13 => Some(F13),
            sdl2::keyboard::Keycode::F14 => Some(F14),
            sdl2::keyboard::Keycode::F15 => Some(F15),
            sdl2::keyboard::Keycode::F16 => Some(F16),
            sdl2::keyboard::Keycode::F17 => Some(F17),
            sdl2::keyboard::Keycode::F18 => Some(F18),
            sdl2::keyboard::Keycode::F19 => Some(F19),
            sdl2::keyboard::Keycode::F20 => Some(F20),
            sdl2::keyboard::Keycode::F21 => Some(F21),
            sdl2::keyboard::Keycode::F22 => Some(F22),
            sdl2::keyboard::Keycode::F23 => Some(F23),
            sdl2::keyboard::Keycode::F24 => Some(F24),
            sdl2::keyboard::Keycode::Execute => Some(Execute),
            sdl2::keyboard::Keycode::Help => Some(Help),
            sdl2::keyboard::Keycode::Menu => Some(Menu),
            sdl2::keyboard::Keycode::Select => Some(Select),
            sdl2::keyboard::Keycode::Stop => Some(Stop),
            sdl2::keyboard::Keycode::Again => Some(Again),
            sdl2::keyboard::Keycode::Undo => Some(Undo),
            sdl2::keyboard::Keycode::Cut => Some(Cut),
            sdl2::keyboard::Keycode::Copy => Some(Copy),
            sdl2::keyboard::Keycode::Paste => Some(Paste),
            sdl2::keyboard::Keycode::Find => Some(Find),
            sdl2::keyboard::Keycode::Mute => Some(Mute),
            sdl2::keyboard::Keycode::VolumeUp => Some(VolumeUp),
            sdl2::keyboard::Keycode::VolumeDown => Some(VolumeDown),
            sdl2::keyboard::Keycode::KpComma => Some(KpComma),
            sdl2::keyboard::Keycode::KpEqualsAS400 => Some(KpEqualsAS400),
            sdl2::keyboard::Keycode::AltErase => Some(AltErase),
            sdl2::keyboard::Keycode::Sysreq => Some(Sysreq),
            sdl2::keyboard::Keycode::Cancel => Some(Cancel),
            sdl2::keyboard::Keycode::Clear => Some(Clear),
            sdl2::keyboard::Keycode::Prior => Some(Prior),
            sdl2::keyboard::Keycode::Return2 => Some(Return2),
            sdl2::keyboard::Keycode::Separator => Some(Separator),
            sdl2::keyboard::Keycode::Out => Some(Out),
            sdl2::keyboard::Keycode::Oper => Some(Oper),
            sdl2::keyboard::Keycode::ClearAgain => Some(ClearAgain),
            sdl2::keyboard::Keycode::CrSel => Some(CrSel),
            sdl2::keyboard::Keycode::ExSel => Some(ExSel),
            sdl2::keyboard::Keycode::Kp00 => Some(Kp00),
            sdl2::keyboard::Keycode::Kp000 => Some(Kp000),
            sdl2::keyboard::Keycode::ThousandsSeparator => Some(ThousandsSeparator),
            sdl2::keyboard::Keycode::DecimalSeparator => Some(DecimalSeparator),
            sdl2::keyboard::Keycode::CurrencyUnit => Some(CurrencyUnit),
            sdl2::keyboard::Keycode::CurrencySubUnit => Some(CurrencySubUnit),
            sdl2::keyboard::Keycode::KpLeftParen => Some(KpLeftParen),
            sdl2::keyboard::Keycode::KpRightParen => Some(KpRightParen),
            sdl2::keyboard::Keycode::KpLeftBrace => Some(KpLeftBrace),
            sdl2::keyboard::Keycode::KpRightBrace => Some(KpRightBrace),
            sdl2::keyboard::Keycode::KpTab => Some(KpTab),
            sdl2::keyboard::Keycode::KpBackspace => Some(KpBackspace),
            sdl2::keyboard::Keycode::KpA => Some(KpA),
            sdl2::keyboard::Keycode::KpB => Some(KpB),
            sdl2::keyboard::Keycode::KpC => Some(KpC),
            sdl2::keyboard::Keycode::KpD => Some(KpD),
            sdl2::keyboard::Keycode::KpE => Some(KpE),
            sdl2::keyboard::Keycode::KpF => Some(KpF),
            sdl2::keyboard::Keycode::KpXor => Some(KpXor),
            sdl2::keyboard::Keycode::KpPower => Some(KpPower),
            sdl2::keyboard::Keycode::KpPercent => Some(KpPercent),
            sdl2::keyboard::Keycode::KpLess => Some(KpLess),
            sdl2::keyboard::Keycode::KpGreater => Some(KpGreater),
            sdl2::keyboard::Keycode::KpAmpersand => Some(KpAmpersand),
            sdl2::keyboard::Keycode::KpDblAmpersand => Some(KpDblAmpersand),
            sdl2::keyboard::Keycode::KpVerticalBar => Some(KpVerticalBar),
            sdl2::keyboard::Keycode::KpDblVerticalBar => Some(KpDblVerticalBar),
            sdl2::keyboard::Keycode::KpColon => Some(KpColon),
            sdl2::keyboard::Keycode::KpHash => Some(KpHash),
            sdl2::keyboard::Keycode::KpSpace => Some(KpSpace),
            sdl2::keyboard::Keycode::KpAt => Some(KpAt),
            sdl2::keyboard::Keycode::KpExclam => Some(KpExclam),
            sdl2::keyboard::Keycode::KpMemStore => Some(KpMemStore),
            sdl2::keyboard::Keycode::KpMemRecall => Some(KpMemRecall),
            sdl2::keyboard::Keycode::KpMemClear => Some(KpMemClear),
            sdl2::keyboard::Keycode::KpMemAdd => Some(KpMemAdd),
            sdl2::keyboard::Keycode::KpMemSubtract => Some(KpMemSubtract),
            sdl2::keyboard::Keycode::KpMemMultiply => Some(KpMemMultiply),
            sdl2::keyboard::Keycode::KpMemDivide => Some(KpMemDivide),
            sdl2::keyboard::Keycode::KpPlusMinus => Some(KpPlusMinus),
            sdl2::keyboard::Keycode::KpClear => Some(KpClear),
            sdl2::keyboard::Keycode::KpClearEntry => Some(KpClearEntry),
            sdl2::keyboard::Keycode::KpBinary => Some(KpBinary),
            sdl2::keyboard::Keycode::KpOctal => Some(KpOctal),
            sdl2::keyboard::Keycode::KpDecimal => Some(KpDecimal),
            sdl2::keyboard::Keycode::KpHexadecimal => Some(KpHexadecimal),
            sdl2::keyboard::Keycode::LCtrl => Some(LCtrl),
            sdl2::keyboard::Keycode::LShift => Some(LShift),
            sdl2::keyboard::Keycode::LAlt => Some(LAlt),
            sdl2::keyboard::Keycode::LGui => Some(LGui),
            sdl2::keyboard::Keycode::RCtrl => Some(RCtrl),
            sdl2::keyboard::Keycode::RShift => Some(RShift),
            sdl2::keyboard::Keycode::RAlt => Some(RAlt),
            sdl2::keyboard::Keycode::RGui => Some(RGui),
            sdl2::keyboard::Keycode::Mode => Some(Mode),
            sdl2::keyboard::Keycode::AudioNext => Some(AudioNext),
            sdl2::keyboard::Keycode::AudioPrev => Some(AudioPrev),
            sdl2::keyboard::Keycode::AudioStop => Some(AudioStop),
            sdl2::keyboard::Keycode::AudioPlay => Some(AudioPlay),
            sdl2::keyboard::Keycode::AudioMute => Some(AudioMute),
            sdl2::keyboard::Keycode::MediaSelect => Some(MediaSelect),
            sdl2::keyboard::Keycode::Www => Some(Www),
            sdl2::keyboard::Keycode::Mail => Some(Mail),
            sdl2::keyboard::Keycode::Calculator => Some(Calculator),
            sdl2::keyboard::Keycode::Computer => Some(Computer),
            sdl2::keyboard::Keycode::AcSearch => Some(AcSearch),
            sdl2::keyboard::Keycode::AcHome => Some(AcHome),
            sdl2::keyboard::Keycode::AcBack => Some(AcBack),
            sdl2::keyboard::Keycode::AcForward => Some(AcForward),
            sdl2::keyboard::Keycode::AcStop => Some(AcStop),
            sdl2::keyboard::Keycode::AcRefresh => Some(AcRefresh),
            sdl2::keyboard::Keycode::AcBookmarks => Some(AcBookmarks),
            sdl2::keyboard::Keycode::BrightnessDown => Some(BrightnessDown),
            sdl2::keyboard::Keycode::BrightnessUp => Some(BrightnessUp),
            sdl2::keyboard::Keycode::DisplaySwitch => Some(DisplaySwitch),
            sdl2::keyboard::Keycode::KbdIllumToggle => Some(KbdIllumToggle),
            sdl2::keyboard::Keycode::KbdIllumDown => Some(KbdIllumDown),
            sdl2::keyboard::Keycode::KbdIllumUp => Some(KbdIllumUp),
            sdl2::keyboard::Keycode::Eject => Some(Eject),
            sdl2::keyboard::Keycode::Sleep => Some(Sleep),
        }
    }
}
impl ToMod for sdl2::keyboard::Mod {
    fn to_mod(&self) -> Option<crate::input::keys::Mod> {
        Mod::from_bits(self.bits())
    }
}
impl ToGamepadButton for sdl2::controller::Button {
    fn to_gamepad_button(&self) -> Option<GamepadButton> {
        use sdl2::controller::Button::*;
        match self {
            A => Some(GamepadButton::A),
            B => Some(GamepadButton::B),
            X => Some(GamepadButton::X),
            Y => Some(GamepadButton::Y),
            Back => Some(GamepadButton::Back),
            Guide => Some(GamepadButton::Guide),
            Start => Some(GamepadButton::Start),
            LeftStick => Some(GamepadButton::LeftStick),
            RightStick => Some(GamepadButton::RightStick),
            LeftShoulder => Some(GamepadButton::LeftShoulder),
            RightShoulder => Some(GamepadButton::RightShoulder),
            DPadUp => Some(GamepadButton::DPadUp),
            DPadDown => Some(GamepadButton::DPadDown),
            DPadLeft => Some(GamepadButton::DPadLeft),
            DPadRight => Some(GamepadButton::DPadRight),
            Misc1 => Some(GamepadButton::Misc1),
            Paddle1 => Some(GamepadButton::Paddle1),
            Paddle2 => Some(GamepadButton::Paddle2),
            Paddle3 => Some(GamepadButton::Paddle3),
            Paddle4 => Some(GamepadButton::Paddle4),
            Touchpad => Some(GamepadButton::Touchpad),
        }
    }
}
